[package]
name = "input_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
binder = { package = "binder_ndk", version = "0.2.0" }

[patch.crates-io]
binder_ndk = { path = "../../rust-deps/binder_rs/binder"}
